@startuml

class Customer{
    id: long
    name: String
}

class Grave{
    id: long
    price: double
}

class Rent{
    id: long
    CustomerId: long
    GraveId: long
    rentStart: LocalDate
    rentEnd: LocalDate
}

class Corpse {
    id: long
    fname: String
    lname: String
    bDate: LocalDate
    deathDate: LocalDate
}

Customer "*"---"*" Grave: mietet >
Rent "*"--"*" Corpse
(Customer, Grave) .. Rent

@enduml